language: python
python:
  - "3.6"

install:
  - pip install -r pandas
  - pip install -r pyodbc
  - pip install -r mysql

# command to run tests
script:
  - python testsuite/unittests/testcleanup.py
  - python testsuite/unittests/teststats.py
  - python testsuite/unittests/testodbc.py
  - python testsuite/unittests/testmysql.py
